cpu-bind=MASK - bp1-compute067, task  0  0 [1992533]: mask 0x400000400000 set
Traceback (most recent call last):
  File "/user/home/zj22662/photon-net/reup_vary_new.py", line 131, in <module>
    data_prod_iterator(varied_list, global_var_name, is_key, log_file, folder, file_indent, start_idx)
  File "/user/home/zj22662/photon-net/reup_vary_new.py", line 98, in data_prod_iterator
    initial_loss, (n0, key) = loss.loss(
                              ^^^^^^^^^^
TypeError: loss() missing 1 required positional argument: 'shuffle_type'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
