cpu-bind=MASK - bp1-compute071, task  0  0 [3374539]: mask 0x40000040 set
Traceback (most recent call last):
  File "/user/home/zj22662/photon-net/reup_python.py", line 2, in <module>
    from p_pack import globals as g
  File "/user/home/zj22662/photon-net/p_pack/globals.py", line 17, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
