cpu-bind=MASK - bp1-compute017, task  0  0 [3077503]: mask 0xfff6000fff6 set
Traceback (most recent call last):
  File "/user/home/zj22662/photon-net/reup_vary_new.py", line 147, in <module>
    data_prod_iterator(varied_list, global_var_name, is_key, log_file, folder, file_indent, start_idx)
  File "/user/home/zj22662/photon-net/reup_vary_new.py", line 113, in data_prod_iterator
    initial_loss, (n0, key) = loss.loss(
                              ^^^^^^^^^^
  File "/user/home/zj22662/photon-net/p_pack/loss.py", line 41, in loss
    _, binary_predictions_plus, n_p, key = model.predict_reupload(phases, data_set, weights, input_config, mask, key, reupload_freq, shuffle_type)
                                                                                                           ^^^^
NameError: name 'mask' is not defined
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
